services:
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5433"